manage of login
rodrigo-calle/repeco-frontend pull request #14
Opened 2021-12-01 16:28 UTC by rodrigo-calle

He agregado data de de usuarios con los datos de email y password los cuales se pueden usar como data de logeo. Asi mismo, hice la validación para el login y agregé una ruta al logeo y home

2021-12-01 17:11 UTC, khriztianmoreno requested changes

2021-12-01 17:11 UTC, khriztianmoreno commented on src/App.js
> +
Que te parece manejar todos los `imports` que son de librerias (react, router, flash, etc) en la parte superior, en todo el top. Luego de estos, si agregar todo lo que corresponda a nuestros `imports` (componentes, estilos, data, etc)?

2021-12-01 17:11 UTC, khriztianmoreno commented on src/components/login/Login.jsx
> +    : console.log(false);
Los operadores ternarios son mas utilizados dentro del `jsx` y su resultado de asigna a una variable, yo te recomiendo cambiar esta implementacion por la forma tradiccional del `IF/ELSE`, ademas ayudara a la lectura del codigo por otro desarrollador.

Que te parece hacerlo de esta forma?

```js
if (validateLogin(email, password)) {
  setTimeout(() => {
    navigate("/") 
  }, 2000); 
} else {
  console.log(false)
} 
```

2021-12-01 18:09 UTC, rodrigo-calle commented on src/App.js
> +
Si me parece lo mejor para llevar un mejor orden, lo modificaré

2021-12-01 18:11 UTC, rodrigo-calle commented on src/components/login/Login.jsx
> +    : console.log(false);
Haré los cambios respectivos a esta parte y tomaré en consideración está forma de escribir condicionales en adelante.

2021-12-03 19:43 UTC, worerxd approved these changes
Buen trabajo

2021-12-03 23:27 UTC, worerxd approved these changes

2021-12-03 23:27 UTC, worerxd approved these changes
Ya está

2021-12-16 15:07 UTC, closed without merging